run-dist:
	./build/install/app/bin/app
run:
	./gradlew run
build:
	./gradlew clean
	./gradlew build
test:
	./gradlew test
lint:
	./gradlew checkstyleMain
test-report:
	./gradlew test
	./gradlew jacocoTestReport

.PHONY: build
.PHONY: test
.PHONY: jacocoTestReport
